services:
  - type: web
    name: dps-ai-challenge-fastapi-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /
